stages:
- name: deploy-app
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: 'export CHART_VERSION=$(grep "version" Chart.yaml | cut -d : -f2)'
    env:
      CHART_VERSION: 1.0.0
  - applyAppConfig:
      catalogTemplate: cattle-global-data:i3s-catalog-openldap
      version: 2.0.3
      answers:
        ldap.bindDN: cn=admin,dc=example,dc=org
        ldap.bindPWKey: LDAP_ADMIN_PASSWORD
        ldap.searchBase: dc=example,dc=org
        ltb-passwd.enabled: "true"
        ltb-passwd.ingress.enabled: "true"
        ltb-passwd.ingress.hosts[0]: ssl-ldap2-test.g3s-service.itcoc.tech
        ltb-passwd.ingress.path: /
        ltb-passwd.ldap.server: ldap://openldap-pipeline
        phpldapadmin.enabled: "true"
        phpldapadmin.env.PHPLDAPADMIN_LDAP_HOSTS: openldap-pipeline
        phpldapadmin.ingress.enabled: "true"
        phpldapadmin.ingress.hosts[0]: phpldapadmin-test.g3s-service.itcoc.tech
      name: openldap-pipeline
      targetNamespace: openldap-pipeline
- name: Tests
  steps:
  - runScriptConfig:
      image: alpine
      shellScript: |-
        apk add openldap-clients
        echo "run ldap commands (add, search, modify...)"
        LDAPTLS_REQCERT=never ldapsearch -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://openldap-pipeline.openldap-pipeline -b 'dc=example,dc=org'
  - applyYamlConfig:
      path: .chaos/failure-experiment.yml
  - runScriptConfig:
      image: alpine
      shellScript: |-
        apk add openldap-clients
        echo "run ldap commands (add, search, modify...)"
        for i in 1 2 3 4 5 6 7 8 9 10
        do
          echo $i
          LDAPTLS_REQCERT=never ldapsearch -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://openldap-pipeline.openldap-pipeline -b 'dc=example,dc=org'
          sleep 60
        done
  - runScriptConfig:
      image: debian:buster
      shellScript: "apt update \napt install -y curl \ncurl -LO https://storage.googleapis.com/kubernetes-release/release/`curl
        -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl\nchmod
        +x ./kubectl \nmv ./kubectl /usr/local/bin/kubectl\nkubectl delete -f .chaos/failure-experiment.yml"
timeout: 60
branch: {}
notification: {}
