stages:
- name: deploy-app
  steps:
  - applyAppConfig:
      catalogTemplate: p-ts7vz:jpg-catalog-openldap
      version: 2.0.2
      answers:
        ldap.bindDN: cn=admin,dc=example,dc=org
        ldap.bindPWKey: LDAP_ADMIN_PASSWORD
        ldap.searchBase: dc=example,dc=org
        ldap.server: ldap://openldap
        ltb-passwd.enabled: "true"
        ltb-passwd.ingress.enabled: "true"
        ltb-passwd.ingress.hosts[0]: ssl-ldap2-test.g3s-service.itcoc.tech
        ltb-passwd.ingress.path: /
        phpldapadmin.enabled: "true"
        phpldapadmin.ingress.enabled: "true"
        phpldapadmin.ingress.hosts[0]: phpldapadmin-test.g3s-service.itcoc.tech
      name: openldap-pipeline
      targetNamespace: openldap-pipeline
  - runScriptConfig:
      image: busybox
      shellScript: 'export CHART_VERSION=$(grep "version" Chart.yaml | cut -d : -f2)'
    env:
      CHART_VERSION: 1.0.0
- name: Tests
  steps:
  - runScriptConfig:
      image: osixia/openldap
      shellScript: |-
        echo "run ldap commands (add, search, modify...)"
        ldapsearch --hostname openldap-pipeline --baseDN "dc=example,dc=org" "(objectclass=*)"
        ldapsearch -x -D "cn=admin,dc=example,dc=org" \
                   -w "Not@SecurePassw0rd" -H ldaps://openldap-pipeline -b "dc=example,dc=org" \
timeout: 60
branch: {}
notification: {}
