apiVersion: v2
name: openldap-stack-ha
dependencies:
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.x
    condition: phpldapadmin.enabled
home: https://www.openldap.org
version: 2.0.4
appVersion: 2.4.47
description: Community developed LDAP software
icon: http://www.openldap.org/images/headers/LDAPworm.gif
keywords:
  - ldap
  - openldap
  - iam-stack
  - high availability 
sources:
  - https://github.com/kubernetes/charts
maintainers:
  - name: Jean-Philippe Gouin
    email: jp-gouin@hotmail.fr
engine: gotpl
