apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-chaos
rules:
- apiGroups:
  - "apps"
  resources:
  - pods
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - chaos-mesh.org
  resources:
  - '*'
  verbs:
  - '*'

