# Default values for ltb-passwd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiredofit/self-service-password
  tag: 5.3.1
  pullPolicy: Always
  pullSecrets: []


nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}
  path: /
  ## Ingress Host
  # hosts:
  # - ssl-ldap.local
  #
  tls: []
  # tls:
  # - secretName: ssl-ldap-dedicated-tls
  #   hosts:
  #   - ssl-ldap.local

# -- Init containers to add to the pod
## Note: Supports use of custom Helm templates
initContainers: []

# -- Additional volumeMounts to the application main container
volumeMounts: []
#  - mountPath: /usr/local/bin/my_tool
#    name: xxxxxx
#    subPath: foo

# -- Additional volumes to the application pod
volumes: []
#  - name: xxxxx
#    emptyDir: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
ldap:
  custom:
    - name: TLS_REQCERT
      value: never
env:
- name: SECRETKEY
  value: "password"
- name: LDAP_LOGIN_ATTRIBUTE
  value: "cn"
- name: LDAP_STARTTLS
  value: "false"
- name: CHANGE_SSHKEY
  value: "true"
